
        List<account> listAcc = new list<account>();

        Account acc = new account();
        acc.name = 'NEW ACCOUNT 1';
        acc.phone = '987654321';
        listAcc.add(acc);

        Account acc1 = new account();
        acc1.name = 'NEW ACCOUNT 2';
        acc1.phone = '987654321';
        listAcc.add(acc1);

        Account acc2 = new account();
        acc2.name = 'NEW ACCOUNT 3';
        acc2.phone = '987654321';
        listAcc.add(acc2);

        insert listAcc;
